target 'Segment-Countly_Example' do
  pod 'Segment-Countly', :path => '../'
end

target 'Segment-Countly_Tests' do
  pod 'Segment-Countly', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
end
